/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatteryCard: typeof import('./src/components/card/BatteryCard.vue')['default']
    DashboardCard: typeof import('./src/components/card/DashboardCard.vue')['default']
    DoughnutChart: typeof import('./src/components/charts/DoughnutChart.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    EnergyCard: typeof import('./src/components/card/EnergyCard.vue')['default']
    FormDialog: typeof import('./src/components/dialog/FormDialog.vue')['default']
    FullSceenDialog: typeof import('./src/components/dialog/fullSceenDialog.vue')['default']
    GlobalLoading: typeof import('./src/components/common/GlobalLoading.vue')['default']
    HeaderCard: typeof import('./src/components/card/headerCard.vue')['default']
    IconButton: typeof import('./src/components/common/IconButton.vue')['default']
    LineChart: typeof import('./src/components/charts/lineChart.vue')['default']
    LoadingBg: typeof import('./src/components/common/LoadingBg.vue')['default']
    ModuleCard: typeof import('./src/components/card/ModuleCard.vue')['default']
    PVCard: typeof import('./src/components/card/PVCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingCard: typeof import('./src/components/card/settingCard.vue')['default']
    SettingItem: typeof import('./src/components/card/settingItem.vue')['default']
    SimpleBarChar: typeof import('./src/components/charts/SimpleBarChar.vue')['default']
    StackedBarChart: typeof import('./src/components/charts/StackedBarChart.vue')['default']
    USAMapChart: typeof import('./src/components/charts/USAMapChart.vue')['default']
  }
}
